build:
  info:
    version: 3.0
cards:
  message: "Welcome to medobank cards related qa APIs "
  contactDetails:
    name: "3M - Developer"
    email: "3m@medobank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345