services:
  accounts:
    build: ./Accounts
    image: "medo3m/accounts:medobank"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - medobank
  loans:
    build: ./Loans
    image: "medo3m/loans:medobank"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - medobank
  cards:
    build: ./Cards
    image: "medo3m/cards:medobank"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - medobank
networks:
  medobank:
    driver: "bridge"