build:
  info:
    version: 1.0
loans:
  message: "Welcome to medobank loans related prod APIs "
  contactDetails:
    name: "Medo - Developer"
    email: "medo@medobank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345