server:
  port: 9010
spring:
  datasource:
    url: ${ACCOUNTS_SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}